//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opinnaytetyo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opiskelija
    {
        public int OpiskelijaID { get; set; }
        public string Etunimi { get; set; }
        public string Sukunimi { get; set; }
        public string Puhelin { get; set; }
        public string Email { get; set; }
        public string Osoite { get; set; }
        public Nullable<int> PostinumeroID { get; set; }
        public string Lisatiedot { get; set; }
    
        public virtual Postitoimipaikat Postitoimipaikat { get; set; }
    }
}
